import './nav.js';
import './hero-slider.js';
import './tours-slider.js';
import './trainers-slider.js';
import './reviews-slider.js';
import './adv-slider.js';
import './gallery-slider.js';
import './form.js';
import './form-focus.js';
